### ISSUE TITLE
Error: Cannot read property '_bound' of undefined

### ISSUE THREAD

**Issue by markoshust** [juliancwirko/react-s-alert#3] opened 2016-01-28 21:48 UTC
Receiving this error on React 0.14.6

```
Error: Cannot read property '_bound' of undefined
TypeError: Cannot read property '_bound' of undefined
    at SAlertContent.handleCloseAlert (SAlertContent.js:75)
    at SAlertContent.js:121
```

**Comment by juliancwirko** [comment] 2016-01-28 21:53
Could you prepare a simple reproduction demo repository? Thanks.

**Comment by juliancwirko** [comment] 2016-02-02 12:22
Does this bug appears in React 0.14.7? 
Because there isn't such bug on [react-s-alert demo repo](https://github.com/juliancwirko/react-s-alert-demo) after `npm update` (actual React is 0.14.7).

**Comment by markoshust** [comment] 2016-02-03 04:42
Hi @juliancwirko -- thanks for response, I was testing before with 0.14.6 but let me test again on 0.14.7.

**Comment by markoshust** [comment] 2016-02-03 16:37
I'm still receiving this error with 0.14.7. The Alert shows, but then when it goes away this error is triggered (on unmount).

**Comment by juliancwirko** [comment] 2016-02-03 16:47
Hey, ok I'll try to reproduce the bug, but without reproduction repo it can take some time :/ because for me unfortunatelly I can't find the bug :/

**Comment by juliancwirko** [comment] 2016-06-22 15:55
I still can't find the error. I will close it. If you feel that it is necessary to re-open, let me know. Thanks.

**Closed by juliancwirko** 2016-06-22 15:55 UTC
Labels: can't reproduce
