### ISSUE TITLE
React 16 support

### ISSUE THREAD

**Issue by martin-svk** [juliancwirko/react-s-alert#49] opened 2017-09-27 13:48 UTC
`react-s-alert@1.3.0 requires a peer of react@^15.0.0 but none was installed`

An update to `package.json` deps should do it.

**Comment by juliancwirko** [comment] 2017-09-27 15:02
Do you use React 16 ? I guess I need to make some updates for React 16

**Comment by stefensuhat** [comment] 2017-09-28 01:28
+1

**Comment by juliancwirko** [comment] 2017-09-28 12:49
there is 1.3.1 version published, let me know if it helps, thanks

**Comment by stefensuhat** [comment] 2017-09-28 13:29
got one more

warning "react-s-alert@1.3.1" has incorrect peer dependency "prop-types@^15.5.4".

**Comment by juliancwirko** [comment] 2017-09-28 14:42
hmmm, strange. I don't see it on clean app created with `create-react-app`. Can you test it on clean app?

**Comment by stefensuhat** [comment] 2017-09-28 14:49
odd. After I've change my prop-type: ^15.6.0 the warning is gone. lol. 

Thanks. no more warning from react-s-alert

**Comment by jayarprado** [comment] 2017-10-03 09:27
When I use this with React 16, my app crashes and I get the following error:
`TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.`

**Comment by juliancwirko** [comment] 2017-10-03 10:07
Interesting, can you test it with fresh, simple React 16 app? Just to eliminate other factors.

**Comment by jayarprado** [comment] 2017-10-03 14:41
@juliancwirko Just tested out a bare minimum usage with `create-react-app`. It gives out the same error. Here are the package versions:

```
dependencies: {
  "react": "^16.0.0",
  "react-dom": "^16.0.0",
  "react-s-alert": "^1.3.1",
  "react-scripts": "1.0.14"
}
```

and the line where the stack trace indicates the error:
`TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.`
```
(anonymous function)
/s-alert-test/node_modules/react-s-alert/dist/s-alert-parts/s-alert-data-prep.js:135
135 | sAlertBoxHeight = parseInt(getComputedStyle(_reactDom2.default.findDOMNode(reactComponent))['height']);
```

**Comment by juliancwirko** [comment] 2017-10-03 14:45
ok, thanks. Could you also post your configuration and how you use it?

**Comment by jayarprado** [comment] 2017-10-03 14:50
@juliancwirko Here's how I used it:

```
import React, { Component } from 'react';

import Alert from 'react-s-alert';
import 'react-s-alert/dist/s-alert-default.css';

class App extends Component {
  componentDidMount() {
    Alert.error("Test message")
  }

  render() {
    return (
      <div className="App">
        <Alert stack={{limit: 3}} />
      </div>
    );
  }
}

export default App;
```

Also, for some reason, it works when I wrap the `Alert` method call with `setTimeout`, like so:
```
componentDidMount() {
  setTimeout(() => Alert.error("Test message"), 0)
}
```

Let me know if you need anything else. Thanks a lot!

**Comment by juliancwirko** [comment] 2017-10-03 17:43
Thanks, I need some time to test it. I'll comment here later.

**Comment by lmeliberty** [comment] 2017-10-04 13:42
@jayarprado Thanks for the temporary solution.

**Comment by anxobotana** [comment] 2017-10-27 09:51
@juliancwirko A nested _requestAnimationFrame_ inside _addToStore_ functions solves the issue.

Something like this:
```javascript
const addToStoreTop = () => {
    requestAnimationFrame( () => requestAnimationFrame( () => {
            let length;
            storeStateTop = getAlertData('full-top') || [];
            length = storeStateTop.length;
            if (this.props.stack && this.props.stack.limit && length > this.props.stack.limit) {
                let id = storeStateTop[0].id;
                sAlertStore.dispatch({type: 'REMOVE', data: {id: id}});
                storeStateTop = getAlertData('full-top') || [];
            }
            this.setState({dataTop: storeStateTop});
    } ) );
};
```

The idea comes from: https://stanko.github.io/react-rerender-in-component-did-mount/

**Comment by juliancwirko** [comment] 2017-10-27 10:06
I hope I'll be able to work on it on this weekend. At least I'll try to provide fix for this bug. Thanks.

**Comment by juliancwirko** [comment] 2017-10-28 12:18
@jayarprado @anxobotana I still can't reproduce that ;) I copied this code:

```javascript
import React, { Component } from 'react';

import Alert from 'react-s-alert';
import 'react-s-alert/dist/s-alert-default.css';

class App extends Component {
  componentDidMount() {
    Alert.error("Test message")
  }

  render() {
    return (
      <div className="App">
        <Alert stack={{limit: 3}} />
      </div>
    );
  }
}

export default App;
```
To my newly created app (totally fresh app created using create-react-app) and it works as it should. I don't get any errors even when using animation effect ;) weird...

I'll try to reproduce it anyway. 

My browser: Chrome 59, 
Deps: "react": "^16.0.0", "react-dom": "^16.0.0", "react-scripts": "1.0.14", newest react-s-alert

**Comment by juliancwirko** [comment] 2017-10-28 13:01
...ok nevermind ;) problem with npm link

**Comment by juliancwirko** [comment] 2017-10-28 14:46
...should be fixed in 1.3.2

**Comment by p1zzadog** [comment] 2017-10-28 15:56
works for me now, thank you!

**Comment by juliancwirko** [comment] 2017-10-30 20:07
I'll close it for now. Feel free to comment here if needed.

**Closed by juliancwirko** 2017-10-30 20:07 UTC
Labels: bug

**Comment by chrisparton1991** [comment] 2017-10-31 10:59
I can also confirm this is fixed, great work!

**Comment by juliancwirko** [comment] 2017-10-31 11:09
cool :) also thanks to @anxobotana :+1:

**Comment by binhnnph03565** [comment] 2018-01-25 07:10
hi ! i setTimeOut for it ' <SAlert effect="stackslide" offset={-10} stack={{ limit: 1 }} timeout={6000} /> ' which it does not receive :(
